/**
 * Public domain book catalog (tier A): typed access to src/pd-catalog.json.
 *
 * The JSON is generated by scripts/pd_catalog_export.py from the backend table
 * `pd_catalog` and overwritten on every export, so nothing here may depend on a
 * particular book being present. The file currently committed is small sample
 * data (`sample: true`, descriptions say so in their own text) so the pages can
 * be built and reviewed before the first export runs.
 *
 * Contract: docs/features/public-domain-books-plan.md, sections 5 and 6.
 */
import catalogJson from './pd-catalog.json';
import { codeToSlug } from './languageSlugs';

export type Cefr = 'A2' | 'B1' | 'B2' | 'C1';

export interface PdAuthor {
  name: string;
  display_name: string;
  birth_year: number | null;
  death_year: number | null;
}

export interface PdMetrics {
  metrics_version: number;
  words: number;
  sentences: number;
  avg_sentence_len: number;
  chapters: number;
  reading_minutes: number;
  zipf_coverage: { z4: number; z3: number } | null;
  cefr_estimate: Cefr | null;
  cefr_confidence: 'low' | 'medium' | 'high';
  pages: number | null;
  has_cover: boolean;
  computed_at: string;
}

export interface PdPair {
  src: string;
  dst: string;
}

export interface PdDescription {
  text: string;
  pairs: PdPair[];
  model?: string;
  generated_at?: string;
}

export interface PdBook {
  id: string;
  slug: string;
  title: string;
  subtitle: string | null;
  authors: PdAuthor[];
  lang: string;
  issued: string | null;
  download_count: number | null;
  subjects: string[];
  bookshelves: string[];
  cover: string | null;
  pages: number | null;
  metrics: PdMetrics;
  descriptions: Record<string, PdDescription>;
  excerpt: string;
}

export interface PdShelf {
  lang: string;
  locales: string[];
  count: number;
}

export interface PdCatalog {
  version: number;
  sample?: boolean;
  generated_at: string;
  shelves: PdShelf[];
  books: PdBook[];
}

export const catalog = catalogJson as unknown as PdCatalog;

export const shelves: PdShelf[] = catalog.shelves ?? [];
export const books: PdBook[] = catalog.books ?? [];

const byIdMap = new Map<string, PdBook>(books.map((b) => [b.id, b]));
const bySlugMap = new Map<string, PdBook>(books.map((b) => [`${b.lang}/${b.slug}`, b]));
const byLangMap = new Map<string, PdBook[]>();
for (const book of books) {
  const list = byLangMap.get(book.lang);
  if (list) list.push(book);
  else byLangMap.set(book.lang, [book]);
}
// Popularity order once, so every shelf and every "similar books" block agrees.
for (const list of byLangMap.values()) {
  list.sort((a, b) => (b.download_count ?? 0) - (a.download_count ?? 0));
}

const shelfByLang = new Map<string, PdShelf>(shelves.map((s) => [s.lang, s]));

/** All books of one shelf language, most downloaded first. */
export function booksByLang(lang: string): PdBook[] {
  return byLangMap.get(lang) ?? [];
}

export function byId(id: string): PdBook | undefined {
  return byIdMap.get(id);
}

/** Slugs are unique per language, so the language pins the lookup. */
export function bySlug(lang: string, slug: string): PdBook | undefined {
  return bySlugMap.get(`${lang}/${slug}`);
}

export function getShelf(lang: string): PdShelf | undefined {
  return shelfByLang.get(lang);
}

/** Shelves that are built in this UI locale (wave 1: only `en`). */
export function shelvesForLocale(locale: string): PdShelf[] {
  return shelves.filter((s) => s.locales.includes(locale));
}

/** UI locales that get at least one shelf, i.e. the locales with a books hub. */
export function localesWithShelves(): string[] {
  const set = new Set<string>();
  for (const shelf of shelves) for (const locale of shelf.locales) set.add(locale);
  return [...set].sort();
}

export function hasShelfInLocale(lang: string, locale: string): boolean {
  return shelfByLang.get(lang)?.locales.includes(locale) ?? false;
}

/** `/en/books/` when that locale owns a shelf, the English hub otherwise. */
export function hubPath(locale: string): string | null {
  if (!shelves.length) return null;
  return localesWithShelves().includes(locale) ? `/${locale}/books/` : '/en/books/';
}

export function shelfPath(locale: string, lang: string): string | null {
  const langSlug = codeToSlug[lang];
  if (!langSlug || !hasShelfInLocale(lang, locale)) return null;
  return `/${locale}/books/${langSlug}/`;
}

export function bookPath(locale: string, book: PdBook): string | null {
  const langSlug = codeToSlug[book.lang];
  if (!langSlug || !hasShelfInLocale(book.lang, locale)) return null;
  return `/${locale}/books/${langSlug}/${book.slug}/`;
}

export const CEFR_ORDER: Cefr[] = ['A2', 'B1', 'B2', 'C1'];

export function levelLabel(book: PdBook): string | null {
  const level = book.metrics?.cefr_estimate ?? null;
  return level && CEFR_ORDER.includes(level) ? level : null;
}

/** "Jane Austen" / "Jane Austen and Lewis Carroll" / "" when unknown. */
export function authorsLine(book: PdBook): string {
  const names = (book.authors ?? []).map((a) => a.display_name || a.name).filter(Boolean);
  if (names.length <= 1) return names[0] ?? '';
  return `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}`;
}

/** "1775-1817", "1775", "": whatever the catalog knows about the first author. */
export function authorYears(book: PdBook): string {
  const author = book.authors?.[0];
  if (!author) return '';
  const { birth_year: birth, death_year: death } = author;
  if (birth && death) return `${birth}-${death}`;
  if (death) return `d. ${death}`;
  if (birth) return `b. ${birth}`;
  return '';
}

export function issuedYear(book: PdBook): string {
  return book.issued ? book.issued.slice(0, 4) : '';
}

/**
 * Books to read next: same language, closest level first, then popularity.
 * The book itself never appears in its own list.
 */
export function similarBooks(book: PdBook, n = 6): PdBook[] {
  const level = levelLabel(book);
  const home = level ? CEFR_ORDER.indexOf(level) : -1;
  const distance = (other: PdBook): number => {
    const otherLevel = levelLabel(other);
    if (home < 0 || !otherLevel) return CEFR_ORDER.length; // unknown level sorts last
    return Math.abs(CEFR_ORDER.indexOf(otherLevel) - home);
  };
  return booksByLang(book.lang)
    .filter((other) => other.id !== book.id)
    .map((other, index) => ({ other, index, dist: distance(other) }))
    // booksByLang is already popularity-sorted, so the stable index breaks ties.
    .sort((a, b) => a.dist - b.dist || a.index - b.index)
    .slice(0, n)
    .map((entry) => entry.other);
}

/** Reading time as "5 h 20 min" / "45 min", built from the metrics estimate. */
export function readingTime(book: PdBook): string {
  const minutes = book.metrics?.reading_minutes ?? 0;
  if (minutes <= 0) return '';
  const hours = Math.floor(minutes / 60);
  const rest = minutes % 60;
  if (!hours) return `${rest} min`;
  return rest ? `${hours} h ${rest} min` : `${hours} h`;
}

/**
 * Title matching for the blog CTA plugin: the same normalization the plugin
 * uses on headings (case, quotes, emphasis marks, collapsed spaces), so a
 * curated title in readingBooks.ts finds its catalog page.
 */
export function normalizeBookTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/[*_"«»„“”'’ʼ]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Exact title match, or one title being the start of the other when it is long
 * enough to be unmistakable (a heading with a trailing note, a catalog title
 * with a subtitle). Loose containment is deliberately not accepted: a wrong
 * book link is worse than no link.
 */
export function findBookByTitle(lang: string, title: string): PdBook | undefined {
  const needle = normalizeBookTitle(title);
  if (!needle) return undefined;
  const LONG_ENOUGH = 10;
  return booksByLang(lang).find((book) => {
    const full = normalizeBookTitle(
      book.subtitle ? `${book.title}: ${book.subtitle}` : book.title,
    );
    const bare = normalizeBookTitle(book.title);
    if (bare === needle || full === needle) return true;
    if (bare.length >= LONG_ENOUGH && needle.startsWith(`${bare} `)) return true;
    if (needle.length >= LONG_ENOUGH && bare.startsWith(`${needle} `)) return true;
    return false;
  });
}

/** `{ pg1342: '/en/books/english/pride-and-prejudice-1342/' }` for the /b/ page. */
export function bookPathsById(locale = 'en'): Record<string, string> {
  const map: Record<string, string> = {};
  for (const book of books) {
    const path = bookPath(locale, book);
    if (path) map[book.id] = path;
  }
  return map;
}
